# Common settings

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

# Transaction executor settings

HealthMonitoringPeriod:
    settings-key: Bitcoin-TransactionsExecutor-HealthMonitoringPeriod

Db:
    AzureDataConnString:
        settings-key: Bitcoin-AzureDataConnString
        types:
            - AzureTableStorage
    LogsConnString:
        settings-key: Bitcoin-LogsConnString
        types:
            - AzureTableStorage
Network:
    settings-key: Bitcoin-Network
Rpc:
    UserName:
        settings-key: Bitcoin-RpcUserName
    Password:
        settings-key: Bitcoin-RpcPassword
    Host:
        settings-key: Bitcoin-RpcHost

FeePerByte:
    settings-key: Bitcoin-TransactionsExecutor-FeePerByte

WarningTimeoutFromLastBlock:
    settings-key: Bitcoin-TransactionsExecutor-NodeReleasesGithubUrl	
    types:
        - Optional